{
 "title": "courier-service",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": " Requests + Retries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(gateway_request_duration_seconds_count{job=\"service-courier\"}[5m])) \r\nby (service, method, grpc_code)",
     "legendFormat": "Requests 🔵 {{service}} {{method}}"
    },
    {
     "expr": "sum(rate(gateway_retries_total{job=\"service-courier\"}[5m])) \r\nby (service, method, reason)",
     "legendFormat": "Retries 🔴 {{service}} {{method}} [{{reason}}]"
    }
   ]
  },
  {
   "title": "P95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"service-courier\"}[5m])) by (le))",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Gateway Latency P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \r\n  sum(rate(gateway_request_duration_seconds_bucket{job=\"service-courier\"}[5m])) \r\n  by (le, service, method, grpc_code)\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests/sec",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"service-courier\"}[5m]))",
     "legendFormat": "Total RPS"
    }
   ]
  },
  {
   "title": "HTTP Request Duration (P98)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.98, sum(rate(http_request_duration_seconds_bucket{job=\"service-courier\"}[5m])) by (le, method, url, status_code))",
     "legendFormat": "{{method}} {{url}} {{status_code}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "system_memory_usage_bytes", "legendFormat": "Memory Usage" }
   ]
  },
  {
   "title": "Rate Limit RPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(rate_limit_exceeded_total{job=\"service-courier\"}[5m])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4xx Client Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"service-courier\",status_code=~\"4..\"}[5m]))",
     "legendFormat": "{{4xx Errors}}"
    }
   ]
  },
  {
   "title": "HTTP Request Count (by method, url, status)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"service-courier\"}[5m])) by (method, url, status_code)",
     "legendFormat": "{{method}} {{url}} {{status_code}}"
    }
   ]
  },
  {
   "title": "CPU Usage Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "system_cpu_usage_percent", "legendFormat": "CPU Usage" }
   ]
  },
  {
   "title": "5xx Server Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"service-courier\",status_code=~\"5..\"}[5m]))",
     "legendFormat": "{{5xx Errors}}"
    }
   ]
  },
  {
   "title": "HTTP Status Codes Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"service-courier\"}[5m])) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_cpu_usage_percent" }
   ]
  }
 ]
}