// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=./contract_mocks_test.go -package=delivery_test
//

// Package delivery_test is a generated GoMock package.
package delivery_test

import (
	context "context"
	reflect "reflect"
	entities "service/internal/entities"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, DeliveryAssignmentEntity entities.DeliveryModify) (*entities.Delivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, DeliveryAssignmentEntity)
	ret0, _ := ret[0].(*entities.Delivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, DeliveryAssignmentEntity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, DeliveryAssignmentEntity)
}

// Delete mocks base method.
func (m *MockRepository) Delete(ctx context.Context, orderID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryMockRecorder) Delete(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository)(nil).Delete), ctx, orderID)
}

// GetCourierForAssignment mocks base method.
func (m *MockRepository) GetCourierForAssignment(ctx context.Context) (*entities.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCourierForAssignment", ctx)
	ret0, _ := ret[0].(*entities.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCourierForAssignment indicates an expected call of GetCourierForAssignment.
func (mr *MockRepositoryMockRecorder) GetCourierForAssignment(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCourierForAssignment", reflect.TypeOf((*MockRepository)(nil).GetCourierForAssignment), ctx)
}

// GetCourierIDAndDeliveryCountByOrderIDForAssing mocks base method.
func (m *MockRepository) GetCourierIDAndDeliveryCountByOrderIDForAssing(ctx context.Context, orderID string) (int64, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCourierIDAndDeliveryCountByOrderIDForAssing", ctx, orderID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetCourierIDAndDeliveryCountByOrderIDForAssing indicates an expected call of GetCourierIDAndDeliveryCountByOrderIDForAssing.
func (mr *MockRepositoryMockRecorder) GetCourierIDAndDeliveryCountByOrderIDForAssing(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCourierIDAndDeliveryCountByOrderIDForAssing", reflect.TypeOf((*MockRepository)(nil).GetCourierIDAndDeliveryCountByOrderIDForAssing), ctx, orderID)
}

// GetCourierIDByOrderID mocks base method.
func (m *MockRepository) GetCourierIDByOrderID(ctx context.Context, orderID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCourierIDByOrderID", ctx, orderID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCourierIDByOrderID indicates an expected call of GetCourierIDByOrderID.
func (mr *MockRepositoryMockRecorder) GetCourierIDByOrderID(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCourierIDByOrderID", reflect.TypeOf((*MockRepository)(nil).GetCourierIDByOrderID), ctx, orderID)
}

// GetLastAssignedDeliveryTime mocks base method.
func (m *MockRepository) GetLastAssignedDeliveryTime(ctx context.Context) (time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastAssignedDeliveryTime", ctx)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastAssignedDeliveryTime indicates an expected call of GetLastAssignedDeliveryTime.
func (mr *MockRepositoryMockRecorder) GetLastAssignedDeliveryTime(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastAssignedDeliveryTime", reflect.TypeOf((*MockRepository)(nil).GetLastAssignedDeliveryTime), ctx)
}

// UpdateCouriersAvailableWhereDeadlineExpired mocks base method.
func (m *MockRepository) UpdateCouriersAvailableWhereDeadlineExpired(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCouriersAvailableWhereDeadlineExpired", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCouriersAvailableWhereDeadlineExpired indicates an expected call of UpdateCouriersAvailableWhereDeadlineExpired.
func (mr *MockRepositoryMockRecorder) UpdateCouriersAvailableWhereDeadlineExpired(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCouriersAvailableWhereDeadlineExpired", reflect.TypeOf((*MockRepository)(nil).UpdateCouriersAvailableWhereDeadlineExpired), ctx)
}

// MockCourierService is a mock of CourierService interface.
type MockCourierService struct {
	ctrl     *gomock.Controller
	recorder *MockCourierServiceMockRecorder
	isgomock struct{}
}

// MockCourierServiceMockRecorder is the mock recorder for MockCourierService.
type MockCourierServiceMockRecorder struct {
	mock *MockCourierService
}

// NewMockCourierService creates a new mock instance.
func NewMockCourierService(ctrl *gomock.Controller) *MockCourierService {
	mock := &MockCourierService{ctrl: ctrl}
	mock.recorder = &MockCourierServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCourierService) EXPECT() *MockCourierServiceMockRecorder {
	return m.recorder
}

// UpdateCourier mocks base method.
func (m *MockCourierService) UpdateCourier(ctx context.Context, courierModify entities.CourierModify) (*entities.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCourier", ctx, courierModify)
	ret0, _ := ret[0].(*entities.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCourier indicates an expected call of UpdateCourier.
func (mr *MockCourierServiceMockRecorder) UpdateCourier(ctx, courierModify any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCourier", reflect.TypeOf((*MockCourierService)(nil).UpdateCourier), ctx, courierModify)
}

// MockDeliveryTimeFactory is a mock of DeliveryTimeFactory interface.
type MockDeliveryTimeFactory struct {
	ctrl     *gomock.Controller
	recorder *MockDeliveryTimeFactoryMockRecorder
	isgomock struct{}
}

// MockDeliveryTimeFactoryMockRecorder is the mock recorder for MockDeliveryTimeFactory.
type MockDeliveryTimeFactoryMockRecorder struct {
	mock *MockDeliveryTimeFactory
}

// NewMockDeliveryTimeFactory creates a new mock instance.
func NewMockDeliveryTimeFactory(ctrl *gomock.Controller) *MockDeliveryTimeFactory {
	mock := &MockDeliveryTimeFactory{ctrl: ctrl}
	mock.recorder = &MockDeliveryTimeFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeliveryTimeFactory) EXPECT() *MockDeliveryTimeFactoryMockRecorder {
	return m.recorder
}

// CalculateDeadline mocks base method.
func (m *MockDeliveryTimeFactory) CalculateDeadline(transportType entities.CourierTransportType, baseTime time.Time) time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateDeadline", transportType, baseTime)
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// CalculateDeadline indicates an expected call of CalculateDeadline.
func (mr *MockDeliveryTimeFactoryMockRecorder) CalculateDeadline(transportType, baseTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateDeadline", reflect.TypeOf((*MockDeliveryTimeFactory)(nil).CalculateDeadline), transportType, baseTime)
}

// MockTxManager is a mock of TxManager interface.
type MockTxManager struct {
	ctrl     *gomock.Controller
	recorder *MockTxManagerMockRecorder
	isgomock struct{}
}

// MockTxManagerMockRecorder is the mock recorder for MockTxManager.
type MockTxManagerMockRecorder struct {
	mock *MockTxManager
}

// NewMockTxManager creates a new mock instance.
func NewMockTxManager(ctrl *gomock.Controller) *MockTxManager {
	mock := &MockTxManager{ctrl: ctrl}
	mock.recorder = &MockTxManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxManager) EXPECT() *MockTxManagerMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockTxManager) Do(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Do indicates an expected call of Do.
func (mr *MockTxManagerMockRecorder) Do(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockTxManager)(nil).Do), ctx, fn)
}
