// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=./contract_mocks_test.go -package=order_test
//

// Package order_test is a generated GoMock package.
package order_test

import (
	context "context"
	reflect "reflect"
	entities "service/internal/entities"
	order "service/internal/service/order"

	gomock "go.uber.org/mock/gomock"
)

// MockOrderGateway is a mock of OrderGateway interface.
type MockOrderGateway struct {
	ctrl     *gomock.Controller
	recorder *MockOrderGatewayMockRecorder
	isgomock struct{}
}

// MockOrderGatewayMockRecorder is the mock recorder for MockOrderGateway.
type MockOrderGatewayMockRecorder struct {
	mock *MockOrderGateway
}

// NewMockOrderGateway creates a new mock instance.
func NewMockOrderGateway(ctrl *gomock.Controller) *MockOrderGateway {
	mock := &MockOrderGateway{ctrl: ctrl}
	mock.recorder = &MockOrderGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderGateway) EXPECT() *MockOrderGatewayMockRecorder {
	return m.recorder
}

// GetOrderByID mocks base method.
func (m *MockOrderGateway) GetOrderByID(ctx context.Context, orderID string) (*entities.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderByID", ctx, orderID)
	ret0, _ := ret[0].(*entities.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderByID indicates an expected call of GetOrderByID.
func (mr *MockOrderGatewayMockRecorder) GetOrderByID(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderByID", reflect.TypeOf((*MockOrderGateway)(nil).GetOrderByID), ctx, orderID)
}

// MockDeliveryService is a mock of DeliveryService interface.
type MockDeliveryService struct {
	ctrl     *gomock.Controller
	recorder *MockDeliveryServiceMockRecorder
	isgomock struct{}
}

// MockDeliveryServiceMockRecorder is the mock recorder for MockDeliveryService.
type MockDeliveryServiceMockRecorder struct {
	mock *MockDeliveryService
}

// NewMockDeliveryService creates a new mock instance.
func NewMockDeliveryService(ctrl *gomock.Controller) *MockDeliveryService {
	mock := &MockDeliveryService{ctrl: ctrl}
	mock.recorder = &MockDeliveryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeliveryService) EXPECT() *MockDeliveryServiceMockRecorder {
	return m.recorder
}

// DeliveryAssign mocks base method.
func (m *MockDeliveryService) DeliveryAssign(ctx context.Context, orderID string) (*entities.DeliveryAssignment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeliveryAssign", ctx, orderID)
	ret0, _ := ret[0].(*entities.DeliveryAssignment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeliveryAssign indicates an expected call of DeliveryAssign.
func (mr *MockDeliveryServiceMockRecorder) DeliveryAssign(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeliveryAssign", reflect.TypeOf((*MockDeliveryService)(nil).DeliveryAssign), ctx, orderID)
}

// DeliveryUnassign mocks base method.
func (m *MockDeliveryService) DeliveryUnassign(ctx context.Context, orderID string) (*entities.DeliveryUnassignment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeliveryUnassign", ctx, orderID)
	ret0, _ := ret[0].(*entities.DeliveryUnassignment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeliveryUnassign indicates an expected call of DeliveryUnassign.
func (mr *MockDeliveryServiceMockRecorder) DeliveryUnassign(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeliveryUnassign", reflect.TypeOf((*MockDeliveryService)(nil).DeliveryUnassign), ctx, orderID)
}

// FreeCourierByOrderID mocks base method.
func (m *MockDeliveryService) FreeCourierByOrderID(ctx context.Context, orderID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FreeCourierByOrderID", ctx, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// FreeCourierByOrderID indicates an expected call of FreeCourierByOrderID.
func (mr *MockDeliveryServiceMockRecorder) FreeCourierByOrderID(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FreeCourierByOrderID", reflect.TypeOf((*MockDeliveryService)(nil).FreeCourierByOrderID), ctx, orderID)
}

// MockHandlerFactory is a mock of HandlerFactory interface.
type MockHandlerFactory struct {
	ctrl     *gomock.Controller
	recorder *MockHandlerFactoryMockRecorder
	isgomock struct{}
}

// MockHandlerFactoryMockRecorder is the mock recorder for MockHandlerFactory.
type MockHandlerFactoryMockRecorder struct {
	mock *MockHandlerFactory
}

// NewMockHandlerFactory creates a new mock instance.
func NewMockHandlerFactory(ctrl *gomock.Controller) *MockHandlerFactory {
	mock := &MockHandlerFactory{ctrl: ctrl}
	mock.recorder = &MockHandlerFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandlerFactory) EXPECT() *MockHandlerFactoryMockRecorder {
	return m.recorder
}

// GetHandler mocks base method.
func (m *MockHandlerFactory) GetHandler(status entities.OrderStatusType) (order.ExecuteFn, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHandler", status)
	ret0, _ := ret[0].(order.ExecuteFn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHandler indicates an expected call of GetHandler.
func (mr *MockHandlerFactoryMockRecorder) GetHandler(status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHandler", reflect.TypeOf((*MockHandlerFactory)(nil).GetHandler), status)
}
