// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=./contract_mocks_test.go -package=delivery_unassign_post_test
//

// Package delivery_unassign_post_test is a generated GoMock package.
package delivery_unassign_post_test

import (
	context "context"
	reflect "reflect"
	entities "service/internal/entities"
	logger "service/pkg/logger"

	gomock "go.uber.org/mock/gomock"
)

// MockhandlerLogger is a mock of handlerLogger interface.
type MockhandlerLogger struct {
	ctrl     *gomock.Controller
	recorder *MockhandlerLoggerMockRecorder
	isgomock struct{}
}

// MockhandlerLoggerMockRecorder is the mock recorder for MockhandlerLogger.
type MockhandlerLoggerMockRecorder struct {
	mock *MockhandlerLogger
}

// NewMockhandlerLogger creates a new mock instance.
func NewMockhandlerLogger(ctrl *gomock.Controller) *MockhandlerLogger {
	mock := &MockhandlerLogger{ctrl: ctrl}
	mock.recorder = &MockhandlerLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockhandlerLogger) EXPECT() *MockhandlerLoggerMockRecorder {
	return m.recorder
}

// Error mocks base method.
func (m *MockhandlerLogger) Error(msg string, fields ...logger.Field) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Error", varargs...)
}

// Error indicates an expected call of Error.
func (mr *MockhandlerLoggerMockRecorder) Error(msg any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockhandlerLogger)(nil).Error), varargs...)
}

// Info mocks base method.
func (m *MockhandlerLogger) Info(msg string, fields ...logger.Field) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Info", varargs...)
}

// Info indicates an expected call of Info.
func (mr *MockhandlerLoggerMockRecorder) Info(msg any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockhandlerLogger)(nil).Info), varargs...)
}

// Warn mocks base method.
func (m *MockhandlerLogger) Warn(msg string, fields ...logger.Field) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Warn", varargs...)
}

// Warn indicates an expected call of Warn.
func (mr *MockhandlerLoggerMockRecorder) Warn(msg any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warn", reflect.TypeOf((*MockhandlerLogger)(nil).Warn), varargs...)
}

// With mocks base method.
func (m *MockhandlerLogger) With(fields ...logger.Field) logger.Logger {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "With", varargs...)
	ret0, _ := ret[0].(logger.Logger)
	return ret0
}

// With indicates an expected call of With.
func (mr *MockhandlerLoggerMockRecorder) With(fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "With", reflect.TypeOf((*MockhandlerLogger)(nil).With), fields...)
}

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// DeliveryUnassign mocks base method.
func (m *MockService) DeliveryUnassign(ctx context.Context, orderId string) (*entities.DeliveryUnassignment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeliveryUnassign", ctx, orderId)
	ret0, _ := ret[0].(*entities.DeliveryUnassignment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeliveryUnassign indicates an expected call of DeliveryUnassign.
func (mr *MockServiceMockRecorder) DeliveryUnassign(ctx, orderId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeliveryUnassign", reflect.TypeOf((*MockService)(nil).DeliveryUnassign), ctx, orderId)
}
